"""Materialize a YOLO-format dataset from a merged train/val index.jsonl.

YOLO trainer expects this layout (Ultralytics convention):

    <root>/
    ├── data.yaml
    ├── images/
    │   ├── train/<stem>.<ext>
    │   └── val/<stem>.<ext>
    └── labels/
        ├── train/<stem>.txt
        └── val/<stem>.txt

The training pipeline is single-class (arthropod, class_id=0). We
symlink images from their source location (chroma-backend
detector_dataset checkout, or Leeds dataset) so we don't duplicate ~1 GB
of jpgs.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from src.localization.leps_data import IndexEntry, materialize_yolo_labels

FG_DATASET_NAMES = (
    "leps-butterflies-500",
    "leps-butterflies-medsmall-1000",
    "leps-butterflies-small-1000",
)


@dataclass
class PrepareCounts:
    train: int
    val: int
    skipped_missing_image: int


def resolve_image_path(
    entry: IndexEntry,
    *,
    fg_root: Path,
    leeds_root: Path | None = None,
) -> Path | None:
    """Locate an entry's image file on disk.

    `fg_root` is the chroma-backend `detector_dataset` checkout root.
    For FG records the path is
    `<fg_root>/datasets/arthropoda/<dataset_name>/images/<image_key>`.
    For Leeds records it's `<leeds_root>/<image_key>` (image_key already
    starts with `images/`).
    """
    if entry.dataset_name in FG_DATASET_NAMES:
        return (
            fg_root
            / "datasets"
            / "arthropoda"
            / entry.dataset_name
            / "images"
            / entry.image_key
        )
    if entry.dataset_name == "leeds-butterflies" and leeds_root is not None:
        return leeds_root / entry.image_key
    return None


def _link_image(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    dst.symlink_to(src.resolve())


def prepare_split(
    entries: Iterable[IndexEntry],
    *,
    images_dir: Path,
    labels_dir: Path,
    fg_root: Path,
    leeds_root: Path | None = None,
) -> tuple[int, int]:
    """Symlink images + write YOLO label .txt files for one split.

    Returns (linked_images, missing_sources).
    """
    images_dir.mkdir(parents=True, exist_ok=True)
    labels_dir.mkdir(parents=True, exist_ok=True)
    linked = 0
    missing = 0
    kept: list[IndexEntry] = []
    for entry in entries:
        src = resolve_image_path(entry, fg_root=fg_root, leeds_root=leeds_root)
        if src is None or not src.exists():
            missing += 1
            continue
        ext = Path(entry.image_key).suffix or ".jpg"
        stem = Path(entry.image_key).stem
        dst = images_dir / f"{stem}{ext}"
        _link_image(src, dst)
        linked += 1
        kept.append(entry)
    materialize_yolo_labels(kept, out_dir=labels_dir, class_id=0)
    return linked, missing


def write_data_yaml(
    path: Path,
    *,
    root: Path,
    class_name: str = "arthropod",
) -> None:
    """Write Ultralytics-style data.yaml for single-class detection."""
    path.parent.mkdir(parents=True, exist_ok=True)
    body = (
        "# Auto-generated by prepare_yolo.py\n"
        f"path: {root.resolve()}\n"
        "train: images/train\n"
        "val: images/val\n"
        "nc: 1\n"
        f"names: ['{class_name}']\n"
    )
    path.write_text(body)


def prepare_yolo_dataset(
    *,
    train_entries: Iterable[IndexEntry],
    val_entries: Iterable[IndexEntry],
    out_root: Path,
    fg_root: Path,
    leeds_root: Path | None = None,
    class_name: str = "arthropod",
) -> PrepareCounts:
    """Top-level driver: build images/{train,val} + labels/{train,val} + data.yaml."""
    train_imgs = out_root / "images" / "train"
    val_imgs = out_root / "images" / "val"
    train_lbls = out_root / "labels" / "train"
    val_lbls = out_root / "labels" / "val"

    train_n, train_missing = prepare_split(
        train_entries,
        images_dir=train_imgs,
        labels_dir=train_lbls,
        fg_root=fg_root,
        leeds_root=leeds_root,
    )
    val_n, val_missing = prepare_split(
        val_entries,
        images_dir=val_imgs,
        labels_dir=val_lbls,
        fg_root=fg_root,
        leeds_root=leeds_root,
    )
    write_data_yaml(out_root / "data.yaml", root=out_root, class_name=class_name)
    return PrepareCounts(
        train=train_n, val=val_n, skipped_missing_image=train_missing + val_missing
    )
